#!/usr/bin/env bash
# tables_t1.sh [<results dir>] - rebuild trials_t1.csv, rounds_t1.csv and summary_t1.md from the raw
# per-trial directories (unpack the <set>.tar.xz first; the in-commit check reads the per-trial logs),
# and append summary_history.md (earlier builds, the review, the bisect).
set -eu
HERE="$(cd "$(dirname "$0")" && pwd)"
R=${1:-$HERE/../../results/20260930_t1}
cd "$R"
SETS="smoke1 mainA mainB neg neg2 f2a lat flap_v22 reg_outlined lat_outlined flap_t1_outlined reg_final flap_t1_final flap_nogid lat_final bisect fetch reg_fixed review flap_fixed fetch_fixed flap_cut25 lat_fixed review2 review3 reg_final2 lat_final2 flap_final2 review4 dci_diag dci_diag2 reg_final3 flap_final3 review5"
D=""
for s in $SETS; do [ -d "$s" ] && D="$D $s"; done
python3 "$HERE/rows_t1.py" $D --trials trials_t1.csv --rounds rounds_t1.csv > /dev/null
S="python3 $HERE/summarize_t1.py"
{
  echo "# NVSHMEM transparent recovery: tables (generated by scripts/t1/tables_t1.sh from the raw logs; sets:$D)"
  echo
  echo "## Outcomes"; echo; $S outcomes trials_t1.csv rounds_t1.csv; echo
  echo "## Recovery rounds (initiator; ms)"; echo; $S rounds trials_t1.csv rounds_t1.csv; echo
  echo "## Application view (transparent trials with a round; ms)"; echo; $S timing trials_t1.csv rounds_t1.csv; echo
  echo "## In-commit shot (F1x5)"; echo; $S incommit trials_t1.csv rounds_t1.csv; echo
  echo "## Address flap"; echo; $S flap trials_t1.csv rounds_t1.csv; echo
  echo "## Fetching atomic in flight (--fetch)"; echo; $S fetch trials_t1.csv rounds_t1.csv; echo
  echo "## Library-socket outage"; echo; $S sock trials_t1.csv rounds_t1.csv; echo
  echo "## DCI resets"; echo; $S dci trials_t1.csv rounds_t1.csv; echo
  echo "## Fault-free latency (set: cell)"; echo
  for s in lat lat_outlined lat_final bisect lat_fixed lat_final2; do
    [ -d "$s" ] || continue
    echo "### $s"; echo
    python3 -c "
import csv,sys
rows=[r for r in csv.DictReader(open('trials_t1.csv')) if r['dir']=='$s']
w=csv.DictWriter(open('.lat_tmp.csv','w'),fieldnames=list(rows[0].keys())); w.writeheader(); [w.writerow(r) for r in rows]"
    $S lat .lat_tmp.csv; rm -f .lat_tmp.csv; echo
  done
  echo; cat "$HERE/summary_history.md"
} > summary_t1.md
echo "wrote $R/summary_t1.md, trials_t1.csv, rounds_t1.csv"
