#!/usr/bin/env bash
# Regenerate every S2 CSV and table from the raw per-trial logs (unpack the <dir>.tar.xz archives first:
# for a in *.tar.xz; do tar xJf $a; done). usage: tables.sh <resultsdir>
set -eu
R=${1:?resultsdir}
D=$(cd "$(dirname "$0")" && pwd)
cd "$R"
for d in lat reg e b c d new; do
  [ -d "$d" ] || continue
  python3 "$D/rows.py" "$d" --out "trials_$d.csv" --rounds "rounds_$d.csv"
done
[ -d bmin ] && python3 "$D/rows_min.py" bmin --out trials_min.csv
{
  echo "# S2 tables (generated by scripts/ts2/tables.sh from the per-trial logs)"
  for d in lat reg e b c d new; do
    [ -f "trials_$d.csv" ] || continue
    echo; echo "## $d"; echo
    g=""; [ "$d" = lat ] && g="--gate gate_test.txt"
    python3 "$D/summarize.py" "trials_$d.csv" --rounds "rounds_$d.csv" $g
  done
  if [ -f trials_min.csv ]; then
    echo; echo "## bmin (the minimal bidirectional program, gpudb build unless the cell says s2)"; echo
    python3 "$D/min_table.py" trials_min.csv
    [ -f two_streams.txt ] && { echo; echo "Two plain kernels on two streams (two_streams_test.cu):"; echo; sed 's/^/    /' two_streams.txt; }
  fi
} > summary.md
echo "wrote $R/summary.md"
